interface IShift {
  id: string;
  status: 'started' | 'finished' | 'preparing';
  title: string;
  final_message: string;
  started_at: string;
  finished_at: string;
  total_users: number;
}

export const data: IShift[] = [
  {
    id: '1',
    status: 'preparing',
    title: 'Весенняя пора',
    final_message: 'все молодцы',
    started_at: '01.05.2022',
    finished_at: '01.06.2022',
    total_users: 153,
  },
  {
    id: '2',
    status: 'started',
    title: 'Летняя пора',
    final_message: 'все молодцы',
    started_at: '02.06.2022',
    finished_at: '01.07.2022',
    total_users: 159,
  },
  {
    id: '3',
    status: 'finished',
    title: 'Летняя пора',
    final_message: 'все молодцы',
    started_at: '02.06.2022',
    finished_at: '01.07.2022',
    total_users: 159,
  },
  {
    id: '4',
    status: 'finished',
    title: 'Летняя пора',
    final_message: 'все молодцы',
    started_at: '02.06.2022',
    finished_at: '01.07.2022',
    total_users: 159,
  },
  {
    id: '5',
    status: 'finished',
    title: 'Летняя пора',
    final_message: 'все молодцы',
    started_at: '02.06.2022',
    finished_at: '01.07.2022',
    total_users: 159,
  },
  {
    id: '6',
    status: 'finished',
    title: 'Летняя пора',
    final_message: 'все молодцы',
    started_at: '02.06.2022',
    finished_at: '01.07.2022',
    total_users: 159,
  },
  {
    id: '7',
    status: 'finished',
    title: 'Летняя пора',
    final_message: 'все молодцы',
    started_at: '02.06.2022',
    finished_at: '01.07.2022',
    total_users: 159,
  },
  {
    id: '8',
    status: 'finished',
    title: 'Летняя пора',
    final_message: 'все молодцы',
    started_at: '02.06.2022',
    finished_at: '01.07.2022',
    total_users: 159,
  },
  {
    id: '9',
    status: 'finished',
    title: 'Летняя пора',
    final_message: 'все молодцы',
    started_at: '02.06.2022',
    finished_at: '01.07.2022',
    total_users: 159,
  },
  {
    id: '10',
    status: 'finished',
    title: 'Летняя пора',
    final_message: 'все молодцы',
    started_at: '02.06.2022',
    finished_at: '01.07.2022',
    total_users: 159,
  },
  {
    id: '11',
    status: 'finished',
    title: 'Летняя пора',
    final_message: 'все молодцы',
    started_at: '02.06.2022',
    finished_at: '01.07.2022',
    total_users: 159,
  },
  {
    id: '12',
    status: 'finished',
    title: 'Летняя пора',
    final_message: 'все молодцы',
    started_at: '02.06.2022',
    finished_at: '01.07.2022',
    total_users: 159,
  },
  // {
  //   id: '2',
  //   status: 'finished',
  //   title: 'Летняя пора',
  //   final_message: 'все молодцы',
  //   started_at: '02.06.2022',
  //   finished_at: '01.07.2022',
  //   total_users: 159,
  // },
  // {
  //   id: '2',
  //   status: 'finished',
  //   title: 'Летняя пора',
  //   final_message: 'все молодцы',
  //   started_at: '02.06.2022',
  //   finished_at: '01.07.2022',
  //   total_users: 159,
  // },
  // {
  //   id: '2',
  //   status: 'finished',
  //   title: 'Летняя пора',
  //   final_message: 'все молодцы',
  //   started_at: '02.06.2022',
  //   finished_at: '01.07.2022',
  //   total_users: 159,
  // },
  // {
  //   id: '2',
  //   status: 'finished',
  //   title: 'Летняя пора',
  //   final_message: 'все молодцы',
  //   started_at: '02.06.2022',
  //   finished_at: '01.07.2022',
  //   total_users: 159,
  // },
  // {
  //   id: '2',
  //   status: 'finished',
  //   title: 'Летняя пора',
  //   final_message: 'все молодцы',
  //   started_at: '02.06.2022',
  //   finished_at: '01.07.2022',
  //   total_users: 159,
  // },
  // {
  //   id: '2',
  //   status: 'finished',
  //   title: 'Летняя пора',
  //   final_message: 'все молодцы',
  //   started_at: '02.06.2022',
  //   finished_at: '01.07.2022',
  //   total_users: 159,
  // },
];
